spring.application.name=gymcheck

# Banco de Dados H2 em Memoria
spring.datasource.url=jdbc:h2:mem:gymcheckdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console Web
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração de atualização do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desativa cache do Thymeleaf em desenvolvimento para atualizar paginas ao salvar
spring.thymeleaf.cache=false